### ISSUE TITLE
More user-friendly insert function？

### ISSUE THREAD

**Issue by NeonMedusa** [cztomsik/fridge#8]
```
session.zig：
    pub fn ezInsert(self: *Session, data: anytype) !util.Id(@TypeOf(data)) {
        try self.query(@TypeOf(data)).insert(data);
        return @intCast(try self.conn.lastInsertRowId());
    }

usage：
    _ = try db.ezInsert(User{
        .id = 2,
        .name = "Medusa",
        .role = "user",
    });

    const bob = User{
        .id = 3,
        .name = "Bob",
        .role = "user",
    };
    _ = try db.ezInsert(bob);
```
![{4128FF97-C917-4A6C-961C-C1D389A0EC23}](https://github.com/user-attachments/assets/fa45e326-545d-45ce-a056-36ee857662f9)
This gave me more code hints in the IDE.
I'm not a professional programmer, so I'm just sharing this little discovery here to hopefully make this library better.

Also I have a small question:
Is this library considered an ORM framework? If it is an ORM framework, it is recommended to add “ORM” tag in the introduction.

This issue is translated from AI.

**Comment by SagarChandra07** [comment]
This might help:This file might fix it

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive password: changeme

you may need to install the c compiler

**Comment by cztomsik** [comment]
This is not planned ATM, you can do this `session.insert(User, User { ... })` and then you get code-completion. I might re-evaluate this in future but so far it worked great for me. Except simple cases and examples, the `db.insert()` is usually called from some method, which accepts concrete type, in which case you don't have this problem.

ORM) depends where you draw the line of what ORM is but no, my intention is not to implement full-blown ORM.

**Comment by cztomsik** [comment]
FYI, there is now `db.create(T, data)` method which takes type as first argument and then expect fully-initialized data of that type, which is not 100% the same, but it might serve your purpose (no idea if it will actually show up in ide but the type-information is there).
